var SEED = {
 "version": 2,
 "trees": [
  {
   "name": "복숭아",
   "aliases": [
    "복숭아"
   ]
  },
  {
   "name": "체리",
   "aliases": [
    "체리",
    "양앵두"
   ]
  },
  {
   "name": "자두",
   "aliases": [
    "자두"
   ]
  },
  {
   "name": "감",
   "aliases": [
    "감",
    "단감"
   ]
  },
  {
   "name": "사과대추",
   "aliases": [
    "대추",
    "사과대추"
   ]
  },
  {
   "name": "딸기",
   "aliases": [
    "딸기"
   ]
  },
  {
   "name": "백일홍",
   "aliases": [
    "배롱나무",
    "백일홍"
   ]
  }
 ],
 "products": [
  {
   "name": "모스피란",
   "kind": "살충",
   "ingredient": "아세타미프리드",
   "content": "8%",
   "form": "수화제",
   "group": "4a",
   "unit": "g",
   "gap": 0,
   "match": [],
   "note": "",
   "source": "제조사 제품 표와 팜모닝 등록 정보 (2026-10 확인)"
  },
  {
   "name": "라이몬",
   "kind": "살충",
   "ingredient": "노발루론",
   "content": "10%",
   "form": "액상수화제",
   "group": "벤조일우레아계",
   "unit": "ml",
   "gap": 0,
   "match": [],
   "note": "",
   "source": "제조사 제품 표와 팜모닝 등록 정보 (2026-10 확인)"
  },
  {
   "name": "알타코아",
   "kind": "살충",
   "ingredient": "클로란트라닐리프롤",
   "content": "5%",
   "form": "입상수화제",
   "group": "28 (디아마이드)",
   "unit": "g",
   "gap": 0,
   "match": [],
   "note": "배수는 라벨 확인",
   "source": "제조사 제품 표와 팜모닝 등록 정보 (2026-10 확인)"
  },
  {
   "name": "델란",
   "kind": "살균",
   "ingredient": "디티아논",
   "content": "75%",
   "form": "수화제",
   "group": "보호 살균제",
   "unit": "g",
   "gap": 0,
   "match": [],
   "note": "석회유황합제, 보르도액, 고착형 전착제와 섞지 않기",
   "source": "제조사 제품 표와 팜모닝 등록 정보 (2026-10 확인)"
  },
  {
   "name": "일품",
   "kind": "살균",
   "ingredient": "옥솔린산",
   "content": "20%",
   "form": "수화제",
   "group": "가4",
   "unit": "g",
   "gap": 0,
   "match": [],
   "note": "",
   "source": "제조사 제품 표와 팜모닝 등록 정보 (2026-10 확인)"
  },
  {
   "name": "살림꾼",
   "kind": "살균",
   "ingredient": "메트코나졸",
   "content": "20%",
   "form": "액상수화제",
   "group": "사1 (트리아졸)",
   "unit": "ml",
   "gap": 0,
   "match": [],
   "note": "",
   "source": "제조사 제품 표와 팜모닝 등록 정보 (2026-10 확인)"
  },
  {
   "name": "후론사이드",
   "kind": "살균",
   "ingredient": "플루아지남",
   "content": "50%",
   "form": "수화제",
   "group": "다5",
   "unit": "g",
   "gap": 0,
   "match": [],
   "note": "배수는 라벨 확인",
   "source": "제조사 제품 표와 팜모닝 등록 정보 (2026-10 확인)"
  },
  {
   "name": "석회보르도액",
   "kind": "살균",
   "ingredient": "석회보르도액",
   "content": "",
   "form": "",
   "group": "",
   "unit": "",
   "gap": 7,
   "match": [
    "보르도",
    "IC66D"
   ],
   "note": "다른 살균제·살충제와 섞지 않고 7일 이상 띄우기. 석회유황합제와도 섞지 않기. 뿌리고 2~3일 안에 비가 오면 약해 우려",
   "source": "제조사 제품 표와 팜모닝 등록 정보 (2026-10 확인)"
  },
  {
   "name": "동제",
   "kind": "살균",
   "ingredient": "구리",
   "content": "",
   "form": "",
   "group": "",
   "unit": "",
   "gap": 7,
   "match": [
    "보르도",
    "코사이드",
    "쿠퍼",
    "구리",
    "동수화제"
   ],
   "note": "보르도액이나 코사이드. 간격 7일은 보르도액 기준을 따른 것이니 라벨 확인",
   "source": ""
  },
  {
   "name": "기계유유제",
   "kind": "동계",
   "ingredient": "기계유",
   "content": "",
   "form": "유제",
   "group": "",
   "unit": "",
   "gap": 14,
   "match": [
    "기계유"
   ],
   "note": "석회유황합제와 2주 이상 띄우기. 배수는 라벨 확인",
   "source": ""
  },
  {
   "name": "석회유황합제",
   "kind": "동계",
   "ingredient": "석회유황",
   "content": "",
   "form": "",
   "group": "",
   "unit": "",
   "gap": 14,
   "match": [
    "석회유황",
    "유황합제"
   ],
   "note": "기계유유제와 2주 이상 띄우기. 싹 트기 전에만",
   "source": ""
  },
  {
   "name": "톱신페스트",
   "kind": "도포",
   "ingredient": "티오파네이트메틸",
   "content": "",
   "form": "도포제",
   "group": "",
   "unit": "",
   "gap": 0,
   "match": [],
   "note": "자른 면과 병든 껍질에 바르는 약",
   "source": ""
  }
 ],
 "doses": [
  {
   "id": "모스피란|복숭아",
   "product": "모스피란",
   "tree": "복숭아",
   "target": "복숭아순나방, 복숭아가루진딧물",
   "dilution": 2000,
   "doseText": "",
   "phi": 21,
   "phiNote": "",
   "max": 3,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "모스피란|자두",
   "product": "모스피란",
   "tree": "자두",
   "target": "",
   "dilution": 2000,
   "doseText": "",
   "phi": 7,
   "phiNote": "",
   "max": 3,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "모스피란|체리",
   "product": "모스피란",
   "tree": "체리",
   "target": "",
   "dilution": 2000,
   "doseText": "",
   "phi": 21,
   "phiNote": "",
   "max": 2,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "모스피란|감",
   "product": "모스피란",
   "tree": "감",
   "target": "",
   "dilution": 2000,
   "doseText": "",
   "phi": 14,
   "phiNote": "",
   "max": 3,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "모스피란|사과대추",
   "product": "모스피란",
   "tree": "사과대추",
   "target": "",
   "dilution": 2000,
   "doseText": "",
   "phi": 21,
   "phiNote": "",
   "max": 2,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "모스피란|딸기",
   "product": "모스피란",
   "tree": "딸기",
   "target": "목화진딧물, 작은뿌리파리",
   "dilution": 2000,
   "doseText": "",
   "phi": 2,
   "phiNote": "",
   "max": 3,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "라이몬|복숭아",
   "product": "라이몬",
   "tree": "복숭아",
   "target": "복숭아순나방, 복숭아심식나방, 복숭아굴나방",
   "dilution": 2000,
   "doseText": "",
   "phi": 21,
   "phiNote": "",
   "max": 3,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "라이몬|자두",
   "product": "라이몬",
   "tree": "자두",
   "target": "",
   "dilution": 2000,
   "doseText": "",
   "phi": 7,
   "phiNote": "",
   "max": 3,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "라이몬|체리",
   "product": "라이몬",
   "tree": "체리",
   "target": "",
   "dilution": 2000,
   "doseText": "",
   "phi": 30,
   "phiNote": "",
   "max": 3,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "라이몬|감",
   "product": "라이몬",
   "tree": "감",
   "target": "",
   "dilution": 2000,
   "doseText": "",
   "phi": 14,
   "phiNote": "",
   "max": 3,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "라이몬|사과대추",
   "product": "라이몬",
   "tree": "사과대추",
   "target": "",
   "dilution": 2000,
   "doseText": "",
   "phi": 21,
   "phiNote": "",
   "max": 3,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "라이몬|딸기",
   "product": "라이몬",
   "tree": "딸기",
   "target": "",
   "dilution": 2000,
   "doseText": "",
   "phi": 3,
   "phiNote": "",
   "max": 3,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "알타코아|복숭아",
   "product": "알타코아",
   "tree": "복숭아",
   "target": "복숭아순나방, 복숭아심식나방, 복숭아유리나방",
   "dilution": null,
   "doseText": "",
   "phi": 7,
   "phiNote": "",
   "max": 3,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "알타코아|자두",
   "product": "알타코아",
   "tree": "자두",
   "target": "",
   "dilution": null,
   "doseText": "",
   "phi": 14,
   "phiNote": "",
   "max": 3,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "알타코아|체리",
   "product": "알타코아",
   "tree": "체리",
   "target": "",
   "dilution": null,
   "doseText": "",
   "phi": 30,
   "phiNote": "",
   "max": 2,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "알타코아|감",
   "product": "알타코아",
   "tree": "감",
   "target": "",
   "dilution": null,
   "doseText": "",
   "phi": 21,
   "phiNote": "",
   "max": 3,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "알타코아|사과대추",
   "product": "알타코아",
   "tree": "사과대추",
   "target": "",
   "dilution": null,
   "doseText": "",
   "phi": 14,
   "phiNote": "",
   "max": 3,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "알타코아|딸기",
   "product": "알타코아",
   "tree": "딸기",
   "target": "",
   "dilution": null,
   "doseText": "",
   "phi": 2,
   "phiNote": "",
   "max": 2,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "델란|복숭아",
   "product": "델란",
   "tree": "복숭아",
   "target": "세균구멍병, 잎오갈병",
   "dilution": 1000,
   "doseText": "",
   "phi": 21,
   "phiNote": "",
   "max": 3,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "델란|체리",
   "product": "델란",
   "tree": "체리",
   "target": "",
   "dilution": 1000,
   "doseText": "",
   "phi": 14,
   "phiNote": "",
   "max": 3,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "델란|감",
   "product": "델란",
   "tree": "감",
   "target": "",
   "dilution": 1000,
   "doseText": "",
   "phi": 21,
   "phiNote": "",
   "max": 4,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "델란|자두",
   "product": "델란",
   "tree": "자두",
   "target": "주머니병",
   "dilution": 1000,
   "doseText": "",
   "phi": null,
   "phiNote": "개화 전",
   "max": 2,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "일품|복숭아",
   "product": "일품",
   "tree": "복숭아",
   "target": "세균구멍병",
   "dilution": 1000,
   "doseText": "",
   "phi": 14,
   "phiNote": "",
   "max": 3,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "일품|자두",
   "product": "일품",
   "tree": "자두",
   "target": "",
   "dilution": 1000,
   "doseText": "",
   "phi": 7,
   "phiNote": "",
   "max": 3,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "일품|체리",
   "product": "일품",
   "tree": "체리",
   "target": "",
   "dilution": 1000,
   "doseText": "",
   "phi": 14,
   "phiNote": "",
   "max": 3,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "살림꾼|복숭아",
   "product": "살림꾼",
   "tree": "복숭아",
   "target": "탄저병, 잿빛무늬병",
   "dilution": 3000,
   "doseText": "",
   "phi": 14,
   "phiNote": "",
   "max": 4,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "살림꾼|자두",
   "product": "살림꾼",
   "tree": "자두",
   "target": "",
   "dilution": 3000,
   "doseText": "",
   "phi": 7,
   "phiNote": "",
   "max": 2,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "살림꾼|체리",
   "product": "살림꾼",
   "tree": "체리",
   "target": "",
   "dilution": 3000,
   "doseText": "",
   "phi": 14,
   "phiNote": "",
   "max": 3,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "살림꾼|감",
   "product": "살림꾼",
   "tree": "감",
   "target": "",
   "dilution": 3000,
   "doseText": "",
   "phi": 14,
   "phiNote": "",
   "max": 4,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "살림꾼|딸기",
   "product": "살림꾼",
   "tree": "딸기",
   "target": "흰가루병",
   "dilution": 3000,
   "doseText": "",
   "phi": 2,
   "phiNote": "",
   "max": 3,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "살림꾼|백일홍",
   "product": "살림꾼",
   "tree": "백일홍",
   "target": "갈색점무늬병",
   "dilution": null,
   "doseText": "",
   "phi": null,
   "phiNote": "",
   "max": null,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "후론사이드|복숭아",
   "product": "후론사이드",
   "tree": "복숭아",
   "target": "잿빛무늬병, 탄저병, 역병",
   "dilution": null,
   "doseText": "",
   "phi": 14,
   "phiNote": "",
   "max": 4,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "후론사이드|자두",
   "product": "후론사이드",
   "tree": "자두",
   "target": "",
   "dilution": null,
   "doseText": "",
   "phi": 7,
   "phiNote": "",
   "max": 3,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "후론사이드|체리",
   "product": "후론사이드",
   "tree": "체리",
   "target": "",
   "dilution": null,
   "doseText": "",
   "phi": 7,
   "phiNote": "",
   "max": 3,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "후론사이드|감",
   "product": "후론사이드",
   "tree": "감",
   "target": "",
   "dilution": null,
   "doseText": "",
   "phi": 21,
   "phiNote": "",
   "max": 4,
   "src": "기준",
   "checked": "",
   "was": ""
  },
  {
   "id": "후론사이드|사과대추",
   "product": "후론사이드",
   "tree": "사과대추",
   "target": "",
   "dilution": null,
   "doseText": "",
   "phi": 30,
   "phiNote": "",
   "max": 3,
   "src": "기준",
   "checked": "",
   "was": ""
  }
 ],
 "mix": [
  {
   "a": "델란",
   "b": "라이몬",
   "verdict": "가능",
   "note": "제조사 혼용표에서 확인 (복숭아)",
   "id": "m01"
  },
  {
   "a": "후론사이드",
   "b": "라이몬",
   "verdict": "가능",
   "note": "제조사 혼용표에서 확인",
   "id": "m02"
  },
  {
   "a": "살림꾼",
   "b": "알타코아",
   "verdict": "가능",
   "note": "제조사 혼용표에서 확인",
   "id": "m03"
  },
  {
   "a": "후론사이드",
   "b": "알타코아",
   "verdict": "가능",
   "note": "제조사 혼용표에서 확인",
   "id": "m04"
  },
  {
   "a": "델란",
   "b": "모스피란",
   "verdict": "확인 안 됨",
   "note": "복숭아에서는 확인하지 못함. 따로 뿌리기",
   "id": "m05"
  },
  {
   "a": "일품",
   "b": "살림꾼",
   "verdict": "확인 안 됨",
   "note": "따로 뿌리기",
   "id": "m06"
  },
  {
   "a": "일품",
   "b": "후론사이드",
   "verdict": "확인 안 됨",
   "note": "따로 뿌리기",
   "id": "m07"
  },
  {
   "a": "일품",
   "b": "라이몬",
   "verdict": "확인 안 됨",
   "note": "따로 뿌리기",
   "id": "m08"
  },
  {
   "a": "일품",
   "b": "알타코아",
   "verdict": "확인 안 됨",
   "note": "따로 뿌리기",
   "id": "m09"
  },
  {
   "a": "일품",
   "b": "모스피란",
   "verdict": "확인 안 됨",
   "note": "따로 뿌리기",
   "id": "m10"
  },
  {
   "a": "살림꾼",
   "b": "모스피란",
   "verdict": "확인 안 됨",
   "note": "따로 뿌리기",
   "id": "m11"
  },
  {
   "a": "석회보르도액",
   "b": "*",
   "verdict": "금지",
   "note": "다른 약과 섞지 않고 7일 이상 띄우기",
   "id": "m12"
  },
  {
   "a": "동제",
   "b": "*",
   "verdict": "금지",
   "note": "보르도액 기준을 따름. 다른 약과 섞지 않기",
   "id": "m13"
  },
  {
   "a": "석회유황합제",
   "b": "*",
   "verdict": "금지",
   "note": "다른 약과 섞지 않기. 기계유유제와 2주 이상",
   "id": "m14"
  },
  {
   "a": "기계유유제",
   "b": "*",
   "verdict": "금지",
   "note": "다른 약과 섞지 않기. 석회유황합제와 2주 이상",
   "id": "m15"
  }
 ],
 "plan": [
  {
   "id": "pe01",
   "tree": "복숭아",
   "kind": "동계",
   "product": "기계유유제",
   "text": "깍지벌레·진딧물 알",
   "note": "영상인 날에. 석회유황합제와 2주 이상 띄우기",
   "s": "12-01",
   "e": "02-28",
   "label": "12월 또는 2월",
   "seq": "",
   "gap": 14,
   "routine": false,
   "post": false
  },
  {
   "id": "pe02",
   "tree": "복숭아",
   "kind": "관리",
   "product": "",
   "text": "전정, 진 흐르는 가지 제거",
   "note": "",
   "s": "12-01",
   "e": "01-31",
   "label": "12월 ~ 1월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pe03",
   "tree": "복숭아",
   "kind": "도포",
   "product": "톱신페스트",
   "text": "진 난 껍질을 긁고 바르기 (수지병)",
   "note": "",
   "s": "01-01",
   "e": "01-31",
   "label": "1월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pe04",
   "tree": "복숭아",
   "kind": "동계",
   "product": "석회유황합제",
   "text": "잎오갈병·구멍병 (핵심)",
   "note": "동제(보르도액·코사이드)로 대신할 수 있음. 기계유유제와 2주 이상 띄우기",
   "s": "03-01",
   "e": "03-31",
   "label": "3월, 싹 트기 직전",
   "seq": "",
   "gap": 14,
   "routine": false,
   "post": false
  },
  {
   "id": "pe05",
   "tree": "복숭아",
   "kind": "주의",
   "product": "",
   "text": "꽃 필 때는 살충제 금지",
   "note": "",
   "s": "04-01",
   "e": "04-30",
   "label": "4월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pe06",
   "tree": "복숭아",
   "kind": "살균",
   "product": "델란",
   "text": "구멍병",
   "note": "",
   "s": "04-21",
   "e": "04-30",
   "label": "4월 하순, 꽃잎이 다 진 직후",
   "seq": "1차",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pe07",
   "tree": "복숭아",
   "kind": "살충",
   "product": "모스피란",
   "text": "진딧물·순나방",
   "note": "꽃이 남아 있으면 미루기",
   "s": "04-21",
   "e": "04-30",
   "label": "4월 하순, 꽃잎이 다 진 직후",
   "seq": "1차",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pe08",
   "tree": "복숭아",
   "kind": "살균",
   "product": "델란",
   "text": "구멍병",
   "note": "",
   "s": "05-01",
   "e": "05-10",
   "label": "5월 상순",
   "seq": "2차",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pe09",
   "tree": "복숭아",
   "kind": "살충",
   "product": "라이몬",
   "text": "순나방 애벌레",
   "note": "",
   "s": "05-01",
   "e": "05-10",
   "label": "5월 상순",
   "seq": "2차",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pe10",
   "tree": "복숭아",
   "kind": "살균",
   "product": "일품",
   "text": "구멍병",
   "note": "",
   "s": "05-21",
   "e": "05-31",
   "label": "5월 하순, 봉지 씌우기 직전",
   "seq": "3차",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pe11",
   "tree": "복숭아",
   "kind": "살균",
   "product": "살림꾼",
   "text": "탄저병",
   "note": "봉지를 씌우면 약이 열매에 닿지 않으니 이 차수는 건너뛰지 않기",
   "s": "05-21",
   "e": "05-31",
   "label": "5월 하순, 봉지 씌우기 직전",
   "seq": "3차",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pe12",
   "tree": "복숭아",
   "kind": "살충",
   "product": "모스피란",
   "text": "진딧물이 남았으면",
   "note": "진딧물이 없으면 쉬기",
   "s": "05-21",
   "e": "05-31",
   "label": "5월 하순, 봉지 씌우기 직전",
   "seq": "3차",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pe13",
   "tree": "복숭아",
   "kind": "관리",
   "product": "",
   "text": "3차 약이 마르면 열매 솎고 봉지 씌우기",
   "note": "",
   "s": "05-21",
   "e": "05-31",
   "label": "5월 하순",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pe14",
   "tree": "복숭아",
   "kind": "살균",
   "product": "일품",
   "text": "구멍병",
   "note": "",
   "s": "06-01",
   "e": "06-10",
   "label": "6월 상순",
   "seq": "4차",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pe15",
   "tree": "복숭아",
   "kind": "살균",
   "product": "후론사이드",
   "text": "탄저병",
   "note": "",
   "s": "06-01",
   "e": "06-10",
   "label": "6월 상순",
   "seq": "4차",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pe16",
   "tree": "복숭아",
   "kind": "살충",
   "product": "라이몬",
   "text": "심식나방",
   "note": "",
   "s": "06-01",
   "e": "06-10",
   "label": "6월 상순",
   "seq": "4차",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pe17",
   "tree": "복숭아",
   "kind": "살균",
   "product": "일품",
   "text": "구멍병",
   "note": "",
   "s": "06-21",
   "e": "06-30",
   "label": "6월 하순, 장마 전",
   "seq": "5차",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pe18",
   "tree": "복숭아",
   "kind": "살균",
   "product": "살림꾼",
   "text": "탄저병",
   "note": "",
   "s": "06-21",
   "e": "06-30",
   "label": "6월 하순, 장마 전",
   "seq": "5차",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pe19",
   "tree": "복숭아",
   "kind": "살충",
   "product": "알타코아",
   "text": "유리나방·심식나방",
   "note": "줄기 밑동과 굵은 가지까지 흠뻑",
   "s": "06-21",
   "e": "06-30",
   "label": "6월 하순, 장마 전",
   "seq": "5차",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pe20",
   "tree": "복숭아",
   "kind": "관리",
   "product": "",
   "text": "줄기 진·톱밥 확인, 애벌레 제거",
   "note": "",
   "s": "06-01",
   "e": "06-30",
   "label": "6월",
   "seq": "",
   "gap": 0,
   "routine": true,
   "post": false
  },
  {
   "id": "pe21",
   "tree": "복숭아",
   "kind": "살균",
   "product": "후론사이드",
   "text": "잿빛무늬병·탄저병",
   "note": "",
   "s": "07-01",
   "e": "07-07",
   "label": "7월 상순, 수확 3주 전",
   "seq": "6차",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pe22",
   "tree": "복숭아",
   "kind": "살충",
   "product": "알타코아",
   "text": "봉지를 안 씌웠으면",
   "note": "봉지를 씌웠으면 쉬기",
   "s": "07-01",
   "e": "07-07",
   "label": "7월 상순, 수확 3주 전",
   "seq": "6차",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pe23",
   "tree": "복숭아",
   "kind": "주의",
   "product": "",
   "text": "모스피란·라이몬은 수확 21일 전까지만 (6차 날이 마지막)",
   "note": "",
   "s": "07-01",
   "e": "07-31",
   "label": "7월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pe24",
   "tree": "복숭아",
   "kind": "살균",
   "product": "살림꾼",
   "text": "잿빛무늬병",
   "note": "살림꾼과 후론사이드는 수확 14일 전까지라 이날로 살균제 끝",
   "s": "07-11",
   "e": "07-14",
   "label": "7월 중순, 수확 2주 전",
   "seq": "7차",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pe25",
   "tree": "복숭아",
   "kind": "관리",
   "product": "",
   "text": "낙과·병든 열매 바로 치우기",
   "note": "",
   "s": "07-01",
   "e": "07-31",
   "label": "7월",
   "seq": "",
   "gap": 0,
   "routine": true,
   "post": false
  },
  {
   "id": "pe26",
   "tree": "복숭아",
   "kind": "관리",
   "product": "",
   "text": "수확",
   "note": "더 늦은 품종이면 계획 시트에서 이 줄의 날짜를 고치고 6차·7차를 수확 3주 전, 2주 전으로 옮기기",
   "s": "07-28",
   "e": "08-10",
   "label": "7월 하순 ~ 8월 상순 (조생종 기준)",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pe27",
   "tree": "복숭아",
   "kind": "살충",
   "product": "라이몬",
   "text": "흰불나방",
   "note": "한 해 3회까지. 열매가 남아 있으면 수확 21일 전까지만",
   "s": "08-11",
   "e": "08-31",
   "label": "8월, 수확을 마친 뒤",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": true
  },
  {
   "id": "pe28",
   "tree": "복숭아",
   "kind": "살충",
   "product": "알타코아",
   "text": "유리나방 2차",
   "note": "줄기에 흠뻑. 열매가 남아 있으면 수확 7일 전까지만",
   "s": "08-11",
   "e": "08-31",
   "label": "8월, 수확을 마친 뒤",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": true
  },
  {
   "id": "pe29",
   "tree": "복숭아",
   "kind": "살충",
   "product": "",
   "text": "응애가 보이면 살비제",
   "note": "",
   "s": "08-01",
   "e": "08-31",
   "label": "8월",
   "seq": "",
   "gap": 0,
   "routine": true,
   "post": false
  },
  {
   "id": "pe30",
   "tree": "복숭아",
   "kind": "살충",
   "product": "모스피란",
   "text": "애매미충",
   "note": "",
   "s": "09-01",
   "e": "09-30",
   "label": "9월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pe31",
   "tree": "복숭아",
   "kind": "살균",
   "product": "석회보르도액",
   "text": "구멍병",
   "note": "4-8식·4-12식. 모스피란을 비롯한 다른 약과 7일 이상 띄우고 섞지 않기. 구멍병이 심했으면 10일 간격으로 2~3회",
   "s": "09-21",
   "e": "10-31",
   "label": "9월 하순 ~ 10월",
   "seq": "",
   "gap": 7,
   "routine": false,
   "post": false
  },
  {
   "id": "pe32",
   "tree": "복숭아",
   "kind": "관리",
   "product": "",
   "text": "떨어진 잎 치우기 (구멍병 월동처)",
   "note": "",
   "s": "10-01",
   "e": "11-30",
   "label": "10월 ~ 11월",
   "seq": "",
   "gap": 0,
   "routine": true,
   "post": false
  },
  {
   "id": "pe33",
   "tree": "복숭아",
   "kind": "살균",
   "product": "동제",
   "text": "가을에 보르도액을 못 쳤으면",
   "note": "보르도액이나 코사이드",
   "s": "11-01",
   "e": "11-30",
   "label": "11월, 낙엽 직후",
   "seq": "",
   "gap": 7,
   "routine": false,
   "post": false
  },
  {
   "id": "ch01",
   "tree": "체리",
   "kind": "동계",
   "product": "기계유유제",
   "text": "깍지벌레·응애 알",
   "note": "영상인 날에. 석회유황합제와 2주 이상 띄우기",
   "s": "12-01",
   "e": "02-28",
   "label": "12월 ~ 2월 중",
   "seq": "",
   "gap": 14,
   "routine": false,
   "post": false
  },
  {
   "id": "ch02",
   "tree": "체리",
   "kind": "관리",
   "product": "",
   "text": "겨울 전정, 진 흐르는 가지 제거",
   "note": "",
   "s": "12-01",
   "e": "01-31",
   "label": "12월 ~ 1월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ch03",
   "tree": "체리",
   "kind": "도포",
   "product": "톱신페스트",
   "text": "자른 면과 병든 껍질에 바르기",
   "note": "",
   "s": "01-01",
   "e": "01-31",
   "label": "1월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ch04",
   "tree": "체리",
   "kind": "동계",
   "product": "석회유황합제",
   "text": "세균성구멍병",
   "note": "동제(보르도액·코사이드)로 대신할 수 있음. 기계유유제와 2주 이상 띄우기",
   "s": "03-01",
   "e": "03-31",
   "label": "3월, 싹 트기 직전",
   "seq": "",
   "gap": 14,
   "routine": false,
   "post": false
  },
  {
   "id": "ch05",
   "tree": "체리",
   "kind": "주의",
   "product": "",
   "text": "꽃 필 때는 살충제 쉬기",
   "note": "",
   "s": "04-01",
   "e": "04-30",
   "label": "4월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ch06",
   "tree": "체리",
   "kind": "살균",
   "product": "",
   "text": "잿빛무늬병 살균제",
   "note": "",
   "s": "04-15",
   "e": "04-30",
   "label": "4월, 꽃이 진 뒤",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ch07",
   "tree": "체리",
   "kind": "살충",
   "product": "모스피란",
   "text": "진딧물",
   "note": "",
   "s": "04-15",
   "e": "04-30",
   "label": "4월, 꽃이 진 뒤",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ch08",
   "tree": "체리",
   "kind": "살균",
   "product": "일품",
   "text": "구멍병",
   "note": "수확 14일 전까지",
   "s": "05-01",
   "e": "05-31",
   "label": "5월, 비 온 뒤",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ch09",
   "tree": "체리",
   "kind": "살충",
   "product": "라이몬",
   "text": "나방 애벌레",
   "note": "수확 30일 전까지만",
   "s": "05-01",
   "e": "05-31",
   "label": "5월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ch10",
   "tree": "체리",
   "kind": "관리",
   "product": "",
   "text": "수확. 익은 열매 바로 따고 낙과 치우기 (초파리)",
   "note": "",
   "s": "06-01",
   "e": "06-30",
   "label": "6월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ch11",
   "tree": "체리",
   "kind": "살균",
   "product": "",
   "text": "갈색무늬병 살균제",
   "note": "",
   "s": "06-01",
   "e": "06-30",
   "label": "6월, 수확 뒤",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": true
  },
  {
   "id": "ch12",
   "tree": "체리",
   "kind": "살충",
   "product": "",
   "text": "유리나방: 줄기에 등록약 흠뻑",
   "note": "",
   "s": "06-01",
   "e": "06-30",
   "label": "6월, 수확 뒤",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": true
  },
  {
   "id": "ch13",
   "tree": "체리",
   "kind": "살균",
   "product": "",
   "text": "갈색무늬병·구멍병 살균제 (조기낙엽 방지)",
   "note": "",
   "s": "07-01",
   "e": "07-31",
   "label": "7월, 장마 전후",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": true
  },
  {
   "id": "ch14",
   "tree": "체리",
   "kind": "관리",
   "product": "",
   "text": "줄기 유리나방 확인",
   "note": "",
   "s": "07-01",
   "e": "07-31",
   "label": "7월",
   "seq": "",
   "gap": 0,
   "routine": true,
   "post": false
  },
  {
   "id": "ch15",
   "tree": "체리",
   "kind": "살균",
   "product": "",
   "text": "조기낙엽 방지 살균제",
   "note": "",
   "s": "08-01",
   "e": "08-31",
   "label": "8월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": true
  },
  {
   "id": "ch16",
   "tree": "체리",
   "kind": "살충",
   "product": "라이몬",
   "text": "흰불나방 2화기",
   "note": "",
   "s": "08-01",
   "e": "08-31",
   "label": "8월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": true
  },
  {
   "id": "ch17",
   "tree": "체리",
   "kind": "살충",
   "product": "",
   "text": "유리나방 2차: 줄기 등록약",
   "note": "",
   "s": "08-01",
   "e": "08-31",
   "label": "8월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": true
  },
  {
   "id": "ch18",
   "tree": "체리",
   "kind": "살충",
   "product": "모스피란",
   "text": "애매미충",
   "note": "",
   "s": "09-01",
   "e": "09-30",
   "label": "9월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": true
  },
  {
   "id": "ch19",
   "tree": "체리",
   "kind": "살충",
   "product": "",
   "text": "응애가 보이면 살비제 (모스피란은 안 들음)",
   "note": "",
   "s": "09-01",
   "e": "09-30",
   "label": "9월",
   "seq": "",
   "gap": 0,
   "routine": true,
   "post": false
  },
  {
   "id": "ch20",
   "tree": "체리",
   "kind": "주의",
   "product": "",
   "text": "잎을 오래 지키기 (내년 꽃눈 양분)",
   "note": "",
   "s": "10-01",
   "e": "10-31",
   "label": "10월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ch21",
   "tree": "체리",
   "kind": "관리",
   "product": "",
   "text": "떨어진 잎 치우기",
   "note": "",
   "s": "10-01",
   "e": "10-31",
   "label": "10월",
   "seq": "",
   "gap": 0,
   "routine": true,
   "post": false
  },
  {
   "id": "ch22",
   "tree": "체리",
   "kind": "살균",
   "product": "동제",
   "text": "낙엽 직후",
   "note": "보르도액이나 코사이드",
   "s": "11-01",
   "e": "11-30",
   "label": "11월, 낙엽 직후",
   "seq": "",
   "gap": 7,
   "routine": false,
   "post": false
  },
  {
   "id": "ch23",
   "tree": "체리",
   "kind": "관리",
   "product": "",
   "text": "낙엽 태우거나 버리기",
   "note": "",
   "s": "11-01",
   "e": "11-30",
   "label": "11월",
   "seq": "",
   "gap": 0,
   "routine": true,
   "post": false
  },
  {
   "id": "pl01",
   "tree": "자두",
   "kind": "동계",
   "product": "기계유유제",
   "text": "",
   "note": "영상인 날에. 석회유황합제와 2주 이상 띄우기",
   "s": "12-01",
   "e": "02-28",
   "label": "12월 ~ 2월 중",
   "seq": "",
   "gap": 14,
   "routine": false,
   "post": false
  },
  {
   "id": "pl02",
   "tree": "자두",
   "kind": "관리",
   "product": "",
   "text": "전정, 검게 마른 가지 제거",
   "note": "",
   "s": "01-01",
   "e": "01-31",
   "label": "1월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pl03",
   "tree": "자두",
   "kind": "도포",
   "product": "톱신페스트",
   "text": "자른 면에 바르기",
   "note": "",
   "s": "01-01",
   "e": "01-31",
   "label": "1월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pl04",
   "tree": "자두",
   "kind": "동계",
   "product": "석회유황합제",
   "text": "주머니병 예방 (핵심)",
   "note": "기계유유제와 2주 이상 띄우기",
   "s": "03-01",
   "e": "03-31",
   "label": "3월, 싹 트기 직전",
   "seq": "",
   "gap": 14,
   "routine": false,
   "post": false
  },
  {
   "id": "pl05",
   "tree": "자두",
   "kind": "살균",
   "product": "",
   "text": "주머니병·잿빛무늬병 살균제",
   "note": "",
   "s": "04-15",
   "e": "04-30",
   "label": "4월, 꽃이 진 뒤",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pl06",
   "tree": "자두",
   "kind": "살충",
   "product": "모스피란",
   "text": "진딧물",
   "note": "",
   "s": "04-15",
   "e": "04-30",
   "label": "4월, 꽃이 진 뒤",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pl07",
   "tree": "자두",
   "kind": "살균",
   "product": "일품",
   "text": "구멍병",
   "note": "수확 7일 전까지",
   "s": "05-01",
   "e": "05-31",
   "label": "5월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pl08",
   "tree": "자두",
   "kind": "관리",
   "product": "",
   "text": "열매 솎기, 봉지 씌우기",
   "note": "",
   "s": "05-01",
   "e": "05-31",
   "label": "5월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pl09",
   "tree": "자두",
   "kind": "살균",
   "product": "",
   "text": "구멍병·검은점무늬병 살균제",
   "note": "",
   "s": "06-01",
   "e": "06-30",
   "label": "6월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pl10",
   "tree": "자두",
   "kind": "살충",
   "product": "",
   "text": "심식나방 살충제",
   "note": "",
   "s": "06-01",
   "e": "06-30",
   "label": "6월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pl11",
   "tree": "자두",
   "kind": "살충",
   "product": "",
   "text": "유리나방: 줄기 밑동에 등록약",
   "note": "",
   "s": "06-01",
   "e": "06-30",
   "label": "6월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pl12",
   "tree": "자두",
   "kind": "관리",
   "product": "",
   "text": "수확. 사용 제한일 확인",
   "note": "",
   "s": "07-01",
   "e": "07-31",
   "label": "7월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pl13",
   "tree": "자두",
   "kind": "살균",
   "product": "",
   "text": "잿빛무늬병 살균제",
   "note": "수확 중이니 사용 제한일 확인",
   "s": "07-01",
   "e": "07-31",
   "label": "7월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "pl14",
   "tree": "자두",
   "kind": "살충",
   "product": "라이몬",
   "text": "흰불나방",
   "note": "",
   "s": "08-01",
   "e": "08-31",
   "label": "8월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": true
  },
  {
   "id": "pl15",
   "tree": "자두",
   "kind": "살충",
   "product": "",
   "text": "응애 관찰",
   "note": "",
   "s": "08-01",
   "e": "08-31",
   "label": "8월",
   "seq": "",
   "gap": 0,
   "routine": true,
   "post": false
  },
  {
   "id": "pl16",
   "tree": "자두",
   "kind": "살충",
   "product": "모스피란",
   "text": "애매미충·선녀벌레",
   "note": "",
   "s": "09-01",
   "e": "09-30",
   "label": "9월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": true
  },
  {
   "id": "pl17",
   "tree": "자두",
   "kind": "관리",
   "product": "",
   "text": "떨어진 잎 치우기",
   "note": "",
   "s": "10-01",
   "e": "10-31",
   "label": "10월",
   "seq": "",
   "gap": 0,
   "routine": true,
   "post": false
  },
  {
   "id": "pl18",
   "tree": "자두",
   "kind": "살균",
   "product": "동제",
   "text": "낙엽 직후",
   "note": "보르도액이나 코사이드",
   "s": "11-01",
   "e": "11-30",
   "label": "11월, 낙엽 직후",
   "seq": "",
   "gap": 7,
   "routine": false,
   "post": false
  },
  {
   "id": "ps01",
   "tree": "감",
   "kind": "관리",
   "product": "",
   "text": "거친 껍질 벗기기 (깍지벌레·노린재 월동처), 전정",
   "note": "",
   "s": "12-01",
   "e": "01-31",
   "label": "12월 ~ 1월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ps02",
   "tree": "감",
   "kind": "동계",
   "product": "기계유유제",
   "text": "깍지벌레",
   "note": "영상인 날에. 석회유황합제와 2주 이상 띄우기",
   "s": "02-01",
   "e": "02-28",
   "label": "2월",
   "seq": "",
   "gap": 14,
   "routine": false,
   "post": false
  },
  {
   "id": "ps03",
   "tree": "감",
   "kind": "동계",
   "product": "석회유황합제",
   "text": "",
   "note": "기계유유제와 2주 이상 띄우기",
   "s": "03-01",
   "e": "03-31",
   "label": "3월, 싹 트기 직전",
   "seq": "",
   "gap": 14,
   "routine": false,
   "post": false
  },
  {
   "id": "ps04",
   "tree": "감",
   "kind": "관리",
   "product": "",
   "text": "새순 해충 관찰",
   "note": "",
   "s": "04-01",
   "e": "04-30",
   "label": "4월",
   "seq": "",
   "gap": 0,
   "routine": true,
   "post": false
  },
  {
   "id": "ps05",
   "tree": "감",
   "kind": "살균",
   "product": "",
   "text": "새 가지 탄저병 예방 살균제",
   "note": "",
   "s": "04-01",
   "e": "04-30",
   "label": "4월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ps06",
   "tree": "감",
   "kind": "살충",
   "product": "모스피란",
   "text": "깍지벌레 어린벌레가 깨는 때",
   "note": "",
   "s": "05-01",
   "e": "06-30",
   "label": "5월 ~ 6월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ps07",
   "tree": "감",
   "kind": "살균",
   "product": "",
   "text": "둥근무늬낙엽병 예방 살균제",
   "note": "",
   "s": "05-21",
   "e": "06-30",
   "label": "5월 하순 ~ 6월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ps08",
   "tree": "감",
   "kind": "살충",
   "product": "",
   "text": "감꼭지나방 1화기 살충제",
   "note": "",
   "s": "06-01",
   "e": "06-30",
   "label": "6월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ps09",
   "tree": "감",
   "kind": "살균",
   "product": "",
   "text": "탄저병·낙엽병 살균제",
   "note": "",
   "s": "07-01",
   "e": "07-31",
   "label": "7월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ps10",
   "tree": "감",
   "kind": "살충",
   "product": "",
   "text": "감꼭지나방 2화기 살충제",
   "note": "",
   "s": "07-01",
   "e": "07-31",
   "label": "7월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ps11",
   "tree": "감",
   "kind": "살균",
   "product": "",
   "text": "탄저병 살균제",
   "note": "",
   "s": "08-01",
   "e": "08-31",
   "label": "8월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ps12",
   "tree": "감",
   "kind": "살충",
   "product": "",
   "text": "노린재 살충제",
   "note": "",
   "s": "08-01",
   "e": "09-30",
   "label": "8월 ~ 9월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ps13",
   "tree": "감",
   "kind": "살충",
   "product": "모스피란",
   "text": "거북밀깍지벌레 어린벌레",
   "note": "",
   "s": "08-01",
   "e": "09-30",
   "label": "8월 ~ 9월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ps14",
   "tree": "감",
   "kind": "살충",
   "product": "",
   "text": "선녀벌레 살충제",
   "note": "",
   "s": "09-01",
   "e": "09-30",
   "label": "9월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ps15",
   "tree": "감",
   "kind": "관리",
   "product": "",
   "text": "수확. 사용 제한일 확인",
   "note": "",
   "s": "10-01",
   "e": "10-31",
   "label": "10월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ps16",
   "tree": "감",
   "kind": "살충",
   "product": "모스피란",
   "text": "깍지벌레가 남았으면",
   "note": "열매를 다 딴 뒤에만",
   "s": "10-01",
   "e": "10-31",
   "label": "10월, 수확을 마친 뒤",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": true
  },
  {
   "id": "ps17",
   "tree": "감",
   "kind": "관리",
   "product": "",
   "text": "낙엽 치우기 (낙엽병 월동처)",
   "note": "",
   "s": "11-01",
   "e": "11-30",
   "label": "11월",
   "seq": "",
   "gap": 0,
   "routine": true,
   "post": false
  },
  {
   "id": "ju01",
   "tree": "사과대추",
   "kind": "관리",
   "product": "",
   "text": "전정, 빗자루병 가지 잘라 태우기",
   "note": "",
   "s": "12-01",
   "e": "01-31",
   "label": "12월 ~ 1월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ju02",
   "tree": "사과대추",
   "kind": "동계",
   "product": "기계유유제",
   "text": "깍지벌레·응애",
   "note": "영상인 날에. 석회유황합제와 2주 이상 띄우기",
   "s": "02-01",
   "e": "02-28",
   "label": "2월",
   "seq": "",
   "gap": 14,
   "routine": false,
   "post": false
  },
  {
   "id": "ju03",
   "tree": "사과대추",
   "kind": "주의",
   "product": "",
   "text": "싹이 늦게 트니 아직 기다리기",
   "note": "",
   "s": "03-01",
   "e": "03-31",
   "label": "3월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ju04",
   "tree": "사과대추",
   "kind": "동계",
   "product": "석회유황합제",
   "text": "",
   "note": "기계유유제와 2주 이상 띄우기",
   "s": "04-01",
   "e": "04-30",
   "label": "4월, 싹 트기 직전",
   "seq": "",
   "gap": 14,
   "routine": false,
   "post": false
  },
  {
   "id": "ju05",
   "tree": "사과대추",
   "kind": "살충",
   "product": "라이몬",
   "text": "잎말이나방",
   "note": "",
   "s": "05-01",
   "e": "05-31",
   "label": "5월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ju06",
   "tree": "사과대추",
   "kind": "살충",
   "product": "",
   "text": "진딧물·응애 관찰",
   "note": "",
   "s": "05-01",
   "e": "05-31",
   "label": "5월",
   "seq": "",
   "gap": 0,
   "routine": true,
   "post": false
  },
  {
   "id": "ju07",
   "tree": "사과대추",
   "kind": "주의",
   "product": "",
   "text": "꽃 필 때는 살충제 쉬기",
   "note": "",
   "s": "06-01",
   "e": "06-30",
   "label": "6월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ju08",
   "tree": "사과대추",
   "kind": "관리",
   "product": "",
   "text": "빗자루병이 의심되면 수간주입 상담",
   "note": "",
   "s": "06-01",
   "e": "06-30",
   "label": "6월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ju09",
   "tree": "사과대추",
   "kind": "살충",
   "product": "",
   "text": "노린재가 오기 시작하는지 보기",
   "note": "",
   "s": "06-01",
   "e": "06-30",
   "label": "6월",
   "seq": "",
   "gap": 0,
   "routine": true,
   "post": false
  },
  {
   "id": "ju10",
   "tree": "사과대추",
   "kind": "살균",
   "product": "",
   "text": "탄저병·녹병 살균제",
   "note": "",
   "s": "07-01",
   "e": "07-31",
   "label": "7월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ju11",
   "tree": "사과대추",
   "kind": "살충",
   "product": "",
   "text": "노린재 살충제",
   "note": "",
   "s": "07-01",
   "e": "07-31",
   "label": "7월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ju12",
   "tree": "사과대추",
   "kind": "살충",
   "product": "",
   "text": "잎말이나방 2화기 살충제",
   "note": "",
   "s": "07-01",
   "e": "07-31",
   "label": "7월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ju13",
   "tree": "사과대추",
   "kind": "살균",
   "product": "",
   "text": "열매 탄저병 살균제",
   "note": "",
   "s": "08-01",
   "e": "08-31",
   "label": "8월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ju14",
   "tree": "사과대추",
   "kind": "살충",
   "product": "",
   "text": "노린재 살충제",
   "note": "",
   "s": "08-01",
   "e": "08-31",
   "label": "8월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ju15",
   "tree": "사과대추",
   "kind": "관리",
   "product": "",
   "text": "수확. 사용 제한일 확인",
   "note": "",
   "s": "09-01",
   "e": "09-30",
   "label": "9월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ju16",
   "tree": "사과대추",
   "kind": "살충",
   "product": "",
   "text": "노린재 살충제",
   "note": "수확 중이니 사용 제한일 확인",
   "s": "09-01",
   "e": "09-30",
   "label": "9월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ju17",
   "tree": "사과대추",
   "kind": "관리",
   "product": "",
   "text": "수확 뒤 정리",
   "note": "",
   "s": "10-01",
   "e": "10-31",
   "label": "10월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "ju18",
   "tree": "사과대추",
   "kind": "살충",
   "product": "모스피란",
   "text": "깍지벌레·애매미충",
   "note": "열매를 다 딴 뒤에만",
   "s": "10-01",
   "e": "10-31",
   "label": "10월, 수확을 마친 뒤",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": true
  },
  {
   "id": "ju19",
   "tree": "사과대추",
   "kind": "관리",
   "product": "",
   "text": "낙엽 치우기 (녹병 월동처)",
   "note": "",
   "s": "11-01",
   "e": "11-30",
   "label": "11월",
   "seq": "",
   "gap": 0,
   "routine": true,
   "post": false
  },
  {
   "id": "ju20",
   "tree": "사과대추",
   "kind": "관리",
   "product": "",
   "text": "빗자루병 가지 표시해 두기",
   "note": "",
   "s": "11-01",
   "e": "11-30",
   "label": "11월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "st01",
   "tree": "딸기",
   "kind": "주의",
   "product": "",
   "text": "월동 중. 덮어 둔 짚·비닐 유지",
   "note": "",
   "s": "12-01",
   "e": "02-28",
   "label": "12월 ~ 2월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "st02",
   "tree": "딸기",
   "kind": "관리",
   "product": "",
   "text": "마른 잎·병든 잎 따 내기",
   "note": "",
   "s": "03-01",
   "e": "03-31",
   "label": "3월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "st03",
   "tree": "딸기",
   "kind": "관리",
   "product": "",
   "text": "보름 간격으로 웃거름 2~3회",
   "note": "",
   "s": "03-15",
   "e": "04-30",
   "label": "3월 중순부터",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "st04",
   "tree": "딸기",
   "kind": "살충",
   "product": "모스피란",
   "text": "꽃 피기 전 진딧물",
   "note": "수확 2일 전까지",
   "s": "04-01",
   "e": "04-20",
   "label": "4월, 꽃 피기 전",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "st05",
   "tree": "딸기",
   "kind": "살충",
   "product": "",
   "text": "응애가 보이면 딸기 등록 살비제",
   "note": "",
   "s": "04-01",
   "e": "04-30",
   "label": "4월",
   "seq": "",
   "gap": 0,
   "routine": true,
   "post": false
  },
  {
   "id": "st06",
   "tree": "딸기",
   "kind": "주의",
   "product": "",
   "text": "꽃이 피면 살충제 금지",
   "note": "",
   "s": "04-01",
   "e": "04-30",
   "label": "4월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "st07",
   "tree": "딸기",
   "kind": "관리",
   "product": "",
   "text": "열매가 흙에 닿지 않게 짚 깔기",
   "note": "",
   "s": "04-01",
   "e": "04-30",
   "label": "4월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "st08",
   "tree": "딸기",
   "kind": "관리",
   "product": "",
   "text": "수확. 무르거나 곰팡이 핀 열매는 바로 따서 버리기",
   "note": "",
   "s": "05-15",
   "e": "06-10",
   "label": "5월 중순 ~ 6월 초순",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "st09",
   "tree": "딸기",
   "kind": "살균",
   "product": "살림꾼",
   "text": "흰가루병",
   "note": "수확 2일 전까지",
   "s": "05-01",
   "e": "05-31",
   "label": "5월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "st10",
   "tree": "딸기",
   "kind": "주의",
   "product": "",
   "text": "약은 수확 2~3일 전 기준인 것만 쓰기",
   "note": "",
   "s": "05-15",
   "e": "06-10",
   "label": "수확하는 동안",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "st11",
   "tree": "딸기",
   "kind": "살충",
   "product": "라이몬",
   "text": "잎 갉는 애벌레",
   "note": "수확 3일 전까지",
   "s": "06-01",
   "e": "06-30",
   "label": "6월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "st12",
   "tree": "딸기",
   "kind": "관리",
   "product": "",
   "text": "수확이 끝나면 런너 정리",
   "note": "",
   "s": "06-11",
   "e": "06-30",
   "label": "6월 중순부터",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "st13",
   "tree": "딸기",
   "kind": "관리",
   "product": "",
   "text": "장마철 탄저병: 시든 포기는 뽑아 버리기",
   "note": "",
   "s": "07-01",
   "e": "07-31",
   "label": "7월",
   "seq": "",
   "gap": 0,
   "routine": true,
   "post": false
  },
  {
   "id": "st14",
   "tree": "딸기",
   "kind": "주의",
   "product": "",
   "text": "물은 잎에 뿌리지 말고 포기 밑에",
   "note": "",
   "s": "07-01",
   "e": "07-31",
   "label": "7월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "st15",
   "tree": "딸기",
   "kind": "관리",
   "product": "",
   "text": "런너에서 새 모종 받기",
   "note": "",
   "s": "08-01",
   "e": "08-31",
   "label": "8월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "st16",
   "tree": "딸기",
   "kind": "관리",
   "product": "",
   "text": "병든 포기·잎 치우기",
   "note": "",
   "s": "08-01",
   "e": "08-31",
   "label": "8월",
   "seq": "",
   "gap": 0,
   "routine": true,
   "post": false
  },
  {
   "id": "st17",
   "tree": "딸기",
   "kind": "관리",
   "product": "",
   "text": "모종 심기",
   "note": "",
   "s": "09-15",
   "e": "10-15",
   "label": "9월 중순 ~ 10월 중순",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "st18",
   "tree": "딸기",
   "kind": "살충",
   "product": "모스피란",
   "text": "진딧물이 보이면 지금 낮춰 두기",
   "note": "",
   "s": "10-01",
   "e": "10-31",
   "label": "10월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "st19",
   "tree": "딸기",
   "kind": "관리",
   "product": "",
   "text": "월동 준비: 짚이나 비닐 덮기",
   "note": "",
   "s": "11-01",
   "e": "11-30",
   "label": "11월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "my01",
   "tree": "백일홍",
   "kind": "동계",
   "product": "기계유유제",
   "text": "월동하는 주머니깍지벌레 알",
   "note": "영상인 날에. 석회유황합제와 2주 이상 띄우기",
   "s": "12-01",
   "e": "02-28",
   "label": "12월 또는 2월",
   "seq": "",
   "gap": 14,
   "routine": false,
   "post": false
  },
  {
   "id": "my02",
   "tree": "백일홍",
   "kind": "관리",
   "product": "",
   "text": "전정, 줄기의 하얀 주머니(깍지벌레)를 솔로 문질러 떼기",
   "note": "",
   "s": "12-01",
   "e": "01-31",
   "label": "12월 ~ 1월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "my03",
   "tree": "백일홍",
   "kind": "관리",
   "product": "",
   "text": "남은 주머니 떼기",
   "note": "",
   "s": "03-01",
   "e": "03-31",
   "label": "3월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "my04",
   "tree": "백일홍",
   "kind": "주의",
   "product": "",
   "text": "싹이 늦게 트니 기다리기. 새순이 나와도 아직 약 없음",
   "note": "",
   "s": "03-01",
   "e": "04-30",
   "label": "3월 ~ 4월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "my05",
   "tree": "백일홍",
   "kind": "관리",
   "product": "",
   "text": "새순에 진딧물이 붙는지, 줄기에 개미가 오르내리는지 확인",
   "note": "",
   "s": "05-01",
   "e": "05-31",
   "label": "5월",
   "seq": "",
   "gap": 0,
   "routine": true,
   "post": false
  },
  {
   "id": "my06",
   "tree": "백일홍",
   "kind": "살충",
   "product": "",
   "text": "주머니깍지벌레: 배롱나무 등록 살충제 1회째",
   "note": "어린벌레가 자리 잡기 전이 적기. 줄기·가지 위주로 흠뻑",
   "s": "06-11",
   "e": "06-20",
   "label": "6월 중순, 알이 깨는 때",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "my07",
   "tree": "백일홍",
   "kind": "살충",
   "product": "",
   "text": "주머니깍지벌레: 배롱나무 등록 살충제 2회째",
   "note": "줄기·가지 위주로 흠뻑",
   "s": "06-21",
   "e": "06-30",
   "label": "1회째에서 10일 뒤",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "my08",
   "tree": "백일홍",
   "kind": "살충",
   "product": "",
   "text": "진딧물이 보이면 살충제",
   "note": "꽃은 피해서 뿌리기",
   "s": "07-01",
   "e": "07-31",
   "label": "7월",
   "seq": "",
   "gap": 0,
   "routine": true,
   "post": false
  },
  {
   "id": "my09",
   "tree": "백일홍",
   "kind": "살균",
   "product": "살림꾼",
   "text": "잎에 갈색 점이 번지면 (갈색점무늬병)",
   "note": "번지지 않으면 쉬기",
   "s": "07-01",
   "e": "07-31",
   "label": "7월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "my10",
   "tree": "백일홍",
   "kind": "살충",
   "product": "",
   "text": "주머니깍지벌레: 살충제 1회째",
   "note": "꽃은 피해서 줄기 위주",
   "s": "08-21",
   "e": "08-31",
   "label": "8월 하순, 두 번째로 알이 깨는 때",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "my11",
   "tree": "백일홍",
   "kind": "관리",
   "product": "",
   "text": "검은 그을음은 호스 물로 씻어 내기",
   "note": "",
   "s": "08-01",
   "e": "08-31",
   "label": "8월",
   "seq": "",
   "gap": 0,
   "routine": true,
   "post": false
  },
  {
   "id": "my12",
   "tree": "백일홍",
   "kind": "살충",
   "product": "",
   "text": "주머니깍지벌레: 살충제 2회째",
   "note": "",
   "s": "09-01",
   "e": "09-10",
   "label": "9월 초순, 8월 하순에서 10일 뒤",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "my13",
   "tree": "백일홍",
   "kind": "주의",
   "product": "",
   "text": "벌레가 줄면 그을음은 비에 서서히 벗겨짐",
   "note": "",
   "s": "09-01",
   "e": "09-30",
   "label": "9월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  },
  {
   "id": "my14",
   "tree": "백일홍",
   "kind": "관리",
   "product": "",
   "text": "떨어진 잎 치우기",
   "note": "",
   "s": "10-01",
   "e": "10-31",
   "label": "10월",
   "seq": "",
   "gap": 0,
   "routine": true,
   "post": false
  },
  {
   "id": "my15",
   "tree": "백일홍",
   "kind": "관리",
   "product": "",
   "text": "낙엽 뒤 줄기의 주머니 확인",
   "note": "",
   "s": "11-01",
   "e": "11-30",
   "label": "11월",
   "seq": "",
   "gap": 0,
   "routine": false,
   "post": false
  }
 ],
 "kit": [
  {
   "id": "k1",
   "name": "모스피란",
   "ingredient": "아세타미프리드",
   "content": "8%",
   "form": "수화제",
   "unit": "",
   "covers": "",
   "status": "확인 전",
   "checked": "",
   "label": null,
   "added": "2026-10-05"
  },
  {
   "id": "k2",
   "name": "라이몬",
   "ingredient": "노발루론",
   "content": "10%",
   "form": "액상수화제",
   "unit": "",
   "covers": "",
   "status": "확인 전",
   "checked": "",
   "label": null,
   "added": "2026-10-05"
  }
 ],
 "photos": [],
 "logs": [],
 "checks": []
};
